[[card]]
title = "Souveränität über Daten und Funktion"
content = "Unsere Kunden behalten die Hoheit über den Code und ihre Daten."
type = "numbered"
color = "seafoam-green"


[[card]]
title = "Kein Lock-In"
content = "Wir bieten Ihnen genau das an, was Sie brauchen: Entwicklung, Hosting, Support, Wartung. Und alles, was Sie selbst regeln wollen, regeln Sie selbst."
type = "numbered"
color = "purple"

[[card]]
title = "Data Science ist Teamsport"
content = "Sie haben das fachliche Know-How und kennen Ihre Daten, wir bringen die methodische und technische Expertise mit. Gemeinsam finden wir eine passende Lösung."
type = "numbered"
color = "sunshine-yellow"

[[card]]
title = "Passender Einsatz von Technologie"
content = "Wir sind Data Scientists und wissen was passt und was nicht passt. Daher wählen wir nicht die auffälligste, sondern die passende Lösung. Ob KI oder ein kleines, gezielt entwickeltes Tool – entscheidend ist, was Ihr Problem nachhaltig löst."
type = "numbered"
color = "deep-violet"

 

