[[card]]
title = ""
content = "Wir entlasten Sie bei Routineaufgaben und ermöglichen <b>Effizienzgewinne und Kostensenkungen</b> durch Automatisierung und Vereinfachung von Verwaltungsprozessen."
type = ""
color = "sunshine-yellow"
link={url="/impressum", text="Kontaktieren Sie uns"}

[[card]]
title = ""
content = "Daten sind unser Spezialgebiet und wir wollen, dass Sie <b>Ihren Datenschatz heben</b>. Wir öffnen Wege für eine bessere und sinnvolle Nutzung von Verwaltungsdaten."
type = ""
color = "seafoam-green"
link={url="/impressum", text="Kontaktieren Sie uns"}

[[card]]
title = ""
content = "Bei uns zahlen Sie NICHT mit Ihren Daten. Sie behalten die volle <b>Souveränität über Daten und Code</b> und bleiben dadurch anbieterunabhängig."
type = ""
color = "purple"
link={url="/impressum", text="Kontaktieren Sie uns"}
