[[card]]
title = ""
content = "Wir wollen Beschäftigte im öffentlichen Sektor zum (besseren) Umgang mit Daten befähigen."
type = ""
color = "sunshine-yellow"
link={url="/impressum", text="Kontaktieren Sie uns"}

[[card]]
title = ""
content = "Wir wollen echte Probleme verstehen und danach gemeinsam pragmatisch lösen."
type = ""
color = "purple"
link={url="/impressum", text="Kontaktieren Sie uns"}

[[card]]
title = ""
content = "Wir wollen Expertise aus verschiedenen Bereichen zusammenbringen."
type = ""
color = "seafoam-green"
link={url="/impressum", text="Kontaktieren Sie uns"}
