[[member]]
name = "Julia von Bartenwerffer"
email = "julia.vonbartenwerffer@ondatix.org"
image = "/images/team/juliavonbartenwerffer_1_1_format_m.jpg"
description = "Julia bringt über 13 Jahre Beratungs- und Projektleitungserfahrung aus Digitalisierungsprojekten mit. Durch ihre Arbeit mit der Initiative ADA Angewandte Datenanalyse für die öffentliche Verwaltung und ihre Masterarbeit zu Datenkompetenz in der ÖV wuchs ihr Antrieb, dieses Wissen für eine bessere und souveräne Datennutzung in Behörden einzusetzen. Bei ondatix ist sie Co-CEO und CFO."
social = [
  { title = "LinkedIn", url = "https://www.linkedin.com/in/julia-von-bartenwerffer-9b5967144/" }
]


[[member]]
name = "Dr. Heidi Seibold"
email = "heidi.seibold@ondatix.org"
image = "/images/team/heidi_seibold_1_1_format.jpg"
description = "Heidi ist Gründerin der Digital Research Academy. Sie ist promovierte Statistikerin und beschäftigt sich heute vorrangig mit der Verbesserung der Qualität in Wissenschaft und Forschung. In ihrem beliebten Newsletter spricht sie über Open Science, gute Wissenschaft und die Zukunft der Forschung. Bei ondatix ist sie Data Scientist und Change‑Management‑Lead."
social = [
  { title = "Website", url = "https://heidiseibold.com/" },
  { title = "LinkedIn", url = "https://www.linkedin.com/in/dr-heidi-seibold/" },
  { title = "Newsletter", url = "https://digiresacademy.kit.com/" }
]

[[member]]
name = "Dr. Jacob Beck"
email = "jacob.beck@ondatix.org"
image = "/images/team/jacob_beck_1_1_format.jpg"
description = "Jacob ist promovierter Statistiker. Seine Forschung konzentriert sich auf Datenqualität in der Entwicklung von KI-Modellen, effektive Mensch-KI-Kollaboration sowie das Brückenbauen zwischen Sozialwissenschaft und Künstlicher Intelligenz. Er war Mitgründer und Projektverantwortlicher des Data Science for Social Good-Programms am Munich Center for Machine Learning. Bei ondatix ist er Co-CEO und Data Scientist."
social = [
  { title = "LinkedIn", url = "https://www.linkedin.com/in/dr-jacob-beck-8b51a5193" }
]

[[member]]
name = "Leonhard Kestel"
email = "leo.kestel@ondatix.org"
image = "/images/team/leokestel_1_1_format_m.jpg"
description = "Leo ist Softwareentwickler und Data Scientist. Neben ondatix promoviert er am Social Data Science and AI (SODA) Lab an der Ludwig-Maximilians-Universität München. Dort beschäftigt er sich mit Neurosymbolischen Methoden für Vertrauenswürdige KI. Fairness und Erklärbarkeit von automatisierten Entscheidungen sind dabei wichtige Aspekte seiner Forschung. Im ADA-Projekt arbeitet er mit Verwaltungsmitarbeitenden an einem sinnvollen Umgang mit Behördendaten. Bei ondatix ist er Lead Developer und CTO."
social = [
  { title = "Website", url = "https://leokestel.de" },
  { title = "LinkedIn", url = "https://www.linkedin.com/in/leonhard-kestel-9aa0bb323/" },
  { title = "GitHub", url = "https://github.com/kestelnadomu" }
]