[[card]]
title = "Interdisziplinarität"
content = "Wir kommen aus unterschiedlichen akademischen Richtungen – von Sozialwissenschaften bis Informatik – und bringen vielfältige Schwerpunkte und Expertisefelder zusammen."
type = "numbered"
color = "salmon"


[[card]]
title = "Fokus"
content = "Uns verbindet ein besonderes Verständnis für die Anforderungen des öffentlichen Sektors."
type = "numbered"
color = "lilac"

[[card]]
title = "Vision"
content = "Und uns eint die Überzeugung: Wenn Daten richtig genutzt werden, wird Verwaltung einfacher, wirksamer und zukunftsfähiger."
type = "numbered"
color = "green"

 

